/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twobulls_myapplication_jni_SimpleJni */

#ifndef _Included_com_twobulls_myapplication_jni_SimpleJni
#define _Included_com_twobulls_myapplication_jni_SimpleJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twobulls_myapplication_jni_SimpleJni
 * Method:    stringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_twobulls_myapplication_jni_SimpleJni_stringFromJni
  (JNIEnv *, jclass);

/*
 * Class:     com_twobulls_myapplication_jni_SimpleJni
 * Method:    unimplementedStringFromJni
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_twobulls_myapplication_jni_SimpleJni_unimplementedStringFromJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
