/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twobulls_myapplication_jni_FFmpegJni */

#ifndef _Included_com_twobulls_myapplication_jni_FFmpegJni
#define _Included_com_twobulls_myapplication_jni_FFmpegJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twobulls_myapplication_jni_FFmpegJni
 * Method:    run
 * Signature: ([Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_twobulls_myapplication_jni_FFmpegJni_run
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
